default: &default
  adapter: mysql2
  username: root
  password: default_password
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: news_development

test:
  <<: *default
  database: news_test

production:
  <<: *default
  database: news_production