production:
  solr:
    hostname: localhost
    port: 8982
    log_level: WARNING
    path: /solr/production

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/default

test:
  solr:
    hostname: localhost
    port: 8982
    log_level: WARNING
    path: /solr/default